### ISSUE TITLE
How to play game?

### ISSUE THREAD

**Issue by Ecdldaiiere** [sarkahn/unityecstetristest#1]
Hi, as someone with not a strong programming background, could you explain to me how I can play your game?

**Comment by sarkahn** [comment]
Hi, I made this many years ago when I was first learning Unity DOTs. It's not really meant to function as a playable game, just a way for me to stumble through the learning process, sorry. I wouldn't recommend it as a learning resource for other people as at that time I made it I had no idea how to write half-decent ECS code.

If you're interested in learning Unity DOTs you should check out [the official forums](https://forum.unity.com/forums/data-oriented-technology-stack.147/) and [Unity ECS Samples repo](https://github.com/Unity-Technologies/EntityComponentSystemSamples).
